### ISSUE TITLE
第三方的插件好像会被 utools 杀后台，官方的可以常驻，有这个情况吧？

### ISSUE THREAD

**Issue by loo100** [ZiuChen/ClipboardManager#35]

**Comment by ZiuChen** [comment]
在插件的设置中开启`跟随主程序启动`即可让插件跟随主程序启动

目前了解到的信息来看：如果后续没有手动结束插件进程，uTools是不会杀后台的。

**Comment by loo100** [comment]
但是确实会丢数据

**Comment by ZiuChen** [comment]
> 但是确实会丢数据

`v1.2.2`正式修复了这个问题，可以通过百度网盘下载离线安装包体验

**Comment by loo100** [comment]
> > 但是确实会丢数据
> 
> `v1.2.2`正式修复了这个问题，可以通过百度网盘下载离线安装包体验

我看已经商城已经更新了 `v1.2.3`，修复了是吧。

**Comment by ZiuChen** [comment]
#28 duplicate
