### ISSUE TITLE
建议左边的蓝色高亮条改为绝对定位不影响主体内容宽度

### ISSUE THREAD

**Issue by Nick-Hopps** [ZiuChen/ClipboardManager#36]
建议左边的蓝色高亮条改为绝对定位不影响主体内容宽度，这样选择的时候内容是静态的，用户体验会更好，现在上下切换选择的时候会有点晕。

**Comment by ZiuChen** [comment]
感谢建议，近一段时间可能不会改动这个部分，如果真的有较多人反映有这种情况，后面会做调整，再次感谢。😉

**Comment by Nick-Hopps** [comment]
好的，谢谢
