### ISSUE TITLE
插件应用‘超级剪切板’装配超时，被强制完全退出

### ISSUE THREAD

**Issue by PixxelSong** [ZiuChen/ClipboardManager#39]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/25476054/192078245-cfa84354-97d6-48da-845f-f6361bc6ff0e.png">

**Comment by ZiuChen** [comment]
尝试删除本地数据库`{home}\_utools_clipboard_manager_storage`后重新启动uTools
[相关链接](https://ziuchen.gitee.io/project/ClipboardManager/guide/)
