### ISSUE TITLE
数据会被粘贴多次

### ISSUE THREAD

**Issue by MatriXiao88** [ZiuChen/ClipboardManager#40]
如下方视频，通过方向键选择数据，然后按下回车使用数据，会出现多条相同数据都被粘贴进来

<img width="243" alt="截屏2022-09-26 23 27 17" src="https://user-images.githubusercontent.com/13702561/192317789-21100470-2269-4abd-815b-ad43632807ac.png">

https://user-images.githubusercontent.com/13702561/192317187-7201cb0c-7721-4224-8285-9ccea65c47c5.mp4

**Comment by ZiuChen** [comment]
感谢反馈！
我尝试了一下：只能偶尔复现，我会尽快排查，下一个版本修复此问题

**Comment by MatriXiao88** [comment]
经过版本1.4.3验证，问题已经fix了，感谢付出！
