### ISSUE TITLE
win11运行后啥也没有

### ISSUE THREAD

**Issue by Sliller** [ZiuChen/ClipboardManager#41]
如题
![image](https://user-images.githubusercontent.com/31638802/192680591-73dca31d-167d-4672-9834-25a85c50e251.png)

**Comment by ZiuChen** [comment]
请尝试删除`{home}\_utools_clipboard_manager_storage`数据库文件后重启插件

**Comment by Sliller** [comment]
> 

好像没有变化，这个文件里内容是这样的。
{"data":[],"createTime":1664343762907,"updateTime":1664343762907}
