### ISSUE TITLE
使用坚果云对剪贴板数据同步不生效

### ISSUE THREAD

**Issue by MatriXiao88** [ZiuChen/ClipboardManager#43]
问题现象：
1. 在mac上装好插件并对_utools_clipboard_manager_storage文件使用坚果云同步
2. 在windows上修改了数据库文件为同步的文件
3. mac上复制数据，windows上要完全退出插件并重启时才能看到mac过来的数据，如果不退出，则看不到
4. 通过坚果云的同步记录，数据库文件是已经触发了同步了，而且windows完全退出后再次进入也能看到新数据，说明含有最新数据的数据库文件已经同步过来了

期望：
能够实时显示出mac上复制的数据

斗胆猜测是插件没有监测数据库文件变更或者监测机制有bug？

**Comment by ZiuChen** [comment]
感谢反馈！数据同步确实存在问题：
本地数据库文件更新了，但是内存中的数据库并没有跟着更新
下一个版本中会做修改：定期用本地数据库的首条记录与内存数据库的首条记录作比较，如果不同则更新内存中的数据库

**Comment by MatriXiao88** [comment]
> 感谢反馈！数据同步确实存在问题： 本地数据库文件更新了，但是内存中的数据库并没有跟着更新 下一个版本中会做修改：定期用本地数据库的首条记录与内存数据库的首条记录作比较，如果不同则更新内存中的数据库

这个策略在某些场景下还是有问题吧，假如内存数据库中的第一条记录值是1，然后数据库中已经更新了好多条数据，但恰好第一条的记录值也是1，那么按照这个策略还是不更新内存，也会导致两边不一致。

建议是用文件watch数据库文件的变更，如果有变更回调，则应该要做一次内存更新了

**Comment by ZiuChen** [comment]
感谢提醒！近期我会尝试用node提供的监听文件变更接口修复此问题 💖

**Comment by ZiuChen** [comment]
`v1.4.5` 已修复
[commit](https://github.com/ZiuChen/ClipboardManager/commit/8ac19335f2d27523a53bd9706553ef18870c8a64)

**Comment by MatriXiao88** [comment]
经过验证，已修复

**Comment by ZiuChen** [comment]
- 是在另一次commit中添加了[调用的代码](https://github.com/ZiuChen/ClipboardManager/blob/2c17bd09d182f624308b803c3196daa0cecc0b91/src/global/initPlugin.js#L46)，在数据库初始化时会开启本地文件的监听，如果文件发生改动会触发一系列的更新
- 我自己在Linux-Win下测试是正常的 😢

**Comment by ZiuChen** [comment]
新版本上线WebDav同步功能
