### ISSUE TITLE
呼出剪贴板没有界面

### ISSUE THREAD

**Issue by zyuerugou** [ZiuChen/ClipboardManager#46]
![image](https://user-images.githubusercontent.com/44331849/196372067-10dfd67d-186e-4735-b93e-48346e2e9ac7.png)

**Comment by zyuerugou** [comment]
v1.4.5
重装也不行，重启utools也不行

**Comment by zyuerugou** [comment]
win10

**Comment by zyuerugou** [comment]
格式化utools内插件数据后重启成功进入正常页面，多谢大佬

**Comment by ZiuChen** [comment]
请问你是会员账户并且使用过uTools提供的同步功能吗？
已经有几位用户反馈这个问题了，我猜测是uTools同步了数据库路径，不同设备上读取同一路径导致出错

**Comment by zyuerugou** [comment]
是的，我是会员，两台电脑的用户不一样，所以可能确实是这个原因



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月19日 15:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ZiuChen/ClipboardManager] 呼出剪贴板没有界面 (Issue #46) |

请问你是会员账户并且使用过uTools提供的同步功能吗？
已经有几位用户反馈这个问题了，我猜测是uTools同步了数据库路径，不同设备上读取同一路径导致出错

**Comment by ZiuChen** [comment]
我在v1.4.6尝试修复了这个问题，我在内测QQ群中发布了pre1的预览版本
欢迎入群下载安装体验 [催更群 769115389](https://qm.qq.com/cgi-bin/qm/qr?k=9qfHKTaQuWqYN1ys1yiQPdJ4iIlHwgL5&jump_from=webapi)

**Comment by ZiuChen** [comment]
fixed in v1.4.6
