### ISSUE TITLE
复制一个40k的json字符串文本之后，插件崩溃

### ISSUE THREAD

**Issue by hinotoyk** [ZiuChen/ClipboardManager#47]
1. 报错信息
<a href="https://ibb.co/8bGTNXT"><img src="https://i.ibb.co/bFYqQ7q/QQ-20221023152726.png" ></a>

2. 打开还是重新安装插件之后再打开，操作界面空白 
<a href="https://ibb.co/TMjbJSf"><img src="https://i.ibb.co/nMdn4vG/QQ-20221023152657.png" ></a>

**Comment by ZiuChen** [comment]
插件读写本地数据库文件出错，请尝试：
① 删除本地数据库文件 `{home}\_utools_clipboard_manager_storage` 后重新启动uTools
② 格式化uTools内的插件数据
[相关链接](https://ziuchen.gitee.io/project/ClipboardManager/guide/)
[参考Issue](https://github.com/ZiuChen/ClipboardManager/issues/39)
