### ISSUE TITLE
开启该插件后 utools.exe 的 CPU 占用率一直较高

### ISSUE THREAD

**Issue by yujunfa** [ZiuChen/ClipboardManager#48]
能够优化或者排查一下原因

**Comment by yujunfa** [comment]
![image](https://user-images.githubusercontent.com/52883968/200486920-5469ecb3-da8d-4939-b5c2-05e898b65e31.png)
不知道是不是这个问题导致的

**Comment by ZiuChen** [comment]
感谢反馈！
关于此问题的具体原因已经在[文档](https://ziuchen.gitee.io/project/ClipboardManager/statement/)中写明

**Comment by yujunfa** [comment]
![image](https://user-images.githubusercontent.com/52883968/200532399-a9b82a7f-88a5-4aae-997e-85fc9a3c921c.png)
版本	Windows 11 专业版
版本	22H2
操作系统版本	22621.755
体验	Windows Feature Experience Pack 1000.22636.1000.0

最新版win11用不了

**Comment by ZiuChen** [comment]
请检查：
1. 是否将handler正确放入了数据库同级位置
2. 是否更新到最新版本
3. 是否尝试重置了uTools内的同步数据
如果上述解决方法都不管用，欢迎入群反馈具体情况

**Comment by yujunfa** [comment]
1、我是因为把文件放到同级后出现了 “白板” 的页面。然后尝试直接执行该exe文件，就弹出 “xxx无法运行xxx”的提示。是最新版的插件。
2、是最新版的插件。
3、同步功能没有开通。

**Comment by ZiuChen** [comment]
请检查：系统进程管理器中是否存在`clipboard-event-handler-xxxxx`的进程

**Comment by yujunfa** [comment]
我按照文档操作的，然后发现卡在那个页面后就去任务管理器中查看了。没找到该进程才去那个数据目录下直接执行，然后就提示无法运行该应用。

**Comment by ZiuChen** [comment]
也许是这个原因，导致插件无法正确执行监听程序
我帮你找到了这个[解决方案](https://blog.csdn.net/qq_44864262/article/details/104420549)，也许你可以尝试一下
