### ISSUE TITLE
按下enter后没有粘贴

### ISSUE THREAD

**Issue by Rico358097990** [ZiuChen/ClipboardManager#49]
环境：win11
通过快捷键拉起本应用，选中记录后点击enter，并不会粘贴

**Comment by ZiuChen** [comment]
请问你的使用场景是什么？

目前已知，在微信聊天框内不会自动粘贴，其他位置的文本框还没有遇到过不能粘贴的情况，都可以执行粘贴。

**Comment by Rico358097990** [comment]
我知道了，我改了键，alt和ctrl互换了，请问有啥解决方案吗

**Comment by ZiuChen** [comment]
因为使用的是uTools提供的粘贴接口，所以目前针对微信聊天框的直接粘贴功能，没有代码上的解决方案
只能复制之后手动粘贴一次
