### ISSUE TITLE
进入V2.0版本后，无法使用快捷键Ctrl+C

### ISSUE THREAD

**Issue by lbkyx** [ZiuChen/ClipboardManager#50]
在[使用指南→快捷键一览](https://ziuchen.gitee.io/project/ClipboardManager/guide/#%E5%BF%AB%E6%8D%B7%E9%94%AE%E4%B8%80%E8%A7%88)中，表明

> ↑ ↓选中历史记录 按下↵直接粘贴 Ctrl+C仅复制

在更新V2.0版本前（旧面板），可以使用快捷键`Ctrl+C`仅复制。进入V2.0版本后，无法使用快捷键`Ctrl+C`。
望修复。谢谢！

**Comment by ZiuChen** [comment]
收到，最近一两个版本会着手修复，感谢反馈

**Comment by lbkyx** [comment]
> 收到，最近一两个版本会着手修复，感谢反馈

已更新新版，看到bug已修复，感谢！
