### ISSUE TITLE
复制的部分图片无法正常预览

### ISSUE THREAD

**Issue by Cypas** [ZiuChen/ClipboardManager#51]
![image](https://user-images.githubusercontent.com/53274578/229470142-114a71c5-8731-49d8-9337-dffca7133a8f.png)
如图，从qq内查看某些图片，并进行复制时，部分图片会以文件类型进入剪切板，而非图片类型，这些文件类型的图片无法正常实现预览
![image](https://user-images.githubusercontent.com/53274578/229471078-49677516-a59a-4075-b935-ff7153eaa3ee.png)
剪贴板监听程序已正常安装

**Comment by ZiuChen** [comment]
从QQ聊天窗口复制的图片本来就是一个图片文件，这是由QQ决定的。
而插件侧不会修改用户的复制内容，也无法对识复制来源进行识别。
