### ISSUE TITLE
复制文本后使用qq截图复制图片, 文本和图片的顺序错乱

### ISSUE THREAD

**Issue by HAndy2013** [ZiuChen/ClipboardManager#52]
### 插件版本: 
v2.1.1
clipboard-event-handler-win32.exe 已配置

### 操作系统: 
windows11 22H2

### 复现步骤:
1. 选中部分文字, ctrl+c 进行复制.
2. 此时立刻使用qq截图工具进行截图.

### 期望行为: 
第二步的截图在剪切板中, 程序的剪切板历史首位是图片.

### 实际行为:
 剪切板中保存的是第一步复制的文字, 程序的剪切板历史第一位是第一步复制的文字, 第二位是最后复制的图片.

**Comment by HAndy2013** [comment]
补充: 复现步骤中的第一步和第二步的间隔时间短, 才会复现

**Comment by HAndy2013** [comment]
再次补充: 有时候, 第一步和第二步间隔时间很久也会发生这种情况, 并且在程序的剪切板历史中, 第一步复制的文本(在首位, 实际应该在第二位)和最后用qq截的图显示的时间都是"刚刚", 实际上是文本的复制是很多分钟之前进行的了

**Comment by ZiuChen** [comment]
未复现😢

**Comment by HAndy2013** [comment]
玄学问题 先关了
