### ISSUE TITLE
MacOS系统无法自定义数据库路径

### ISSUE THREAD

**Issue by xwyam** [ZiuChen/ClipboardManager#54]
MacOS版本：13.3.1
utools版本：3.3.0
Clipboard版本：2.1.4

配置界面数据库路径点击“修改”按钮后，整个界面为灰色，没有选择路径窗口出现
![image](https://github.com/ZiuChen/ClipboardManager/assets/2004930/30942081-05bd-4e72-85dd-34ba09e1c783)

**Comment by ZiuChen** [comment]
fixed
