### ISSUE TITLE
我编译了一个适用于mac-apple-silicon-arm64-M系列，剪贴板监听程序clipboard-event-handler-mac

### ISSUE THREAD

**Issue by wade6716** [ZiuChen/ClipboardManager#55]
我编译了一个适用于mac apple-silicon-arm64-M系列处理器的剪贴板监听程序clipboard-event-handler-mac
获取地址及说明 https://github.com/wangyw6716/clipboard-event-handler-mac-apple-silicon-arm64-M1
希望作者收录到使用说明中，让使用arm64 mac的朋友不用转译Intel程序，效果图如下，谢谢！

![image](https://github.com/ZiuChen/ClipboardManager/assets/59910348/335610a4-a518-4c52-b921-2c30cd7b8c94)

<img width="388" alt="image" src="https://github.com/ZiuChen/ClipboardManager/assets/59910348/6927086d-8bcb-4cdb-9903-56df0dc07c3a">

直接使用原作者的Intel版本效果如下图所示，需要依赖于Rosetta 2

![image](https://github.com/ZiuChen/ClipboardManager/assets/59910348/909eb8ae-382b-4aa7-b769-5b7fc64d889c)

**Comment by ZiuChen** [comment]
感谢，文档已经补充相关内容：https://ziuchen.github.io/project/ClipboardManager/guide/
