### ISSUE TITLE
剪贴板收藏文字后，可以提供编辑的功能不

### ISSUE THREAD

**Issue by iknownoth1ng** [ZiuChen/ClipboardManager#56]
有时候收藏了一大段经常使用的文字内容，可能其中某一两个有用的信息发生了变更。
这个时候想编辑一下收藏的文字。
可以增加一个编辑的功能不，
或者是哪里有编辑的功能，但是我没有找到。

**Comment by ZiuChen** [comment]
这个场景下编辑功能确实有必要 后面会尝试做一下收藏内容的编辑功能

> 目前没有编辑功能，可以将旧的内容复制出来，在其他位置编辑好后复制新的内容，将新的内容添加收藏

但是说实话 这个场景下 用快贴也许更合适

**Comment by ZiuChen** [comment]
新版已支持编辑
