### ISSUE TITLE
webdav图片同步问题

### ISSUE THREAD

**Issue by HopeLHP** [ZiuChen/ClipboardManager#59]
其他渠道实在联系不上作者，只能来这里了。
问题：
截图复制图片后webdav总是提示上传失败error：invalid response：400，用的坚果云会员，应该没有限制。
复制文字没有问题，复制截图的图片后打开剪贴板就提示这些。

**Comment by ZiuChen** [comment]
Windows 系统可能存在图片上传/下载失败的问题
预计在下个版本（v2.4.0）集中修复WebDAV的相关问题，可以到时观察下，感谢！

**Comment by ZiuChen** [comment]
fixed
