### ISSUE TITLE
:bug: 复制大文本后，一直弹窗

### ISSUE THREAD

**Issue by zhongjun96** [ZiuChen/ClipboardManager#60]
Mac 14.2 (23C64)
uTools V4.4.1
应用版本 v2.3.3
![image](https://github.com/ZiuChen/ClipboardManager/assets/18225577/98c6a3fc-837c-498a-993c-fd3cbc31fafe)

**Comment by ZiuChen** [comment]
v2.3.4 已优化大文本弹窗的问题
