### ISSUE TITLE
收藏的条目，可以自己拖动排序吗

### ISSUE THREAD

**Issue by iknownoth1ng** [ZiuChen/ClipboardManager#61]
问题：
1. 之前的收藏，条目是会根据使用程度自动排到第一位
2. 最新版的v2.3.3，收藏条目会排在最后一位，且没法置顶。

希望：
1. 收藏是否可以自定义拖动顺序，或者有个置顶功能也行。

**Comment by ZiuChen** [comment]
v2.3.4 优化了收藏的排序规则，会在被筛选时根据上次使用频次排序
收藏内容本质上是剪贴板的另一种表现形式，要实现自定义顺序可能要新开插件来用另一套来做
