### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by shadowmimosa** [ZiuChen/ClipboardManager#62]
**问题描述:**

将硬盘放到另一台电脑上运行该硬盘上的系统时，出现以下报错：

![image](https://github.com/ZiuChen/ClipboardManager/assets/38422761/0e3fb520-e01b-4f50-b263-94964c837138)

**问题分析:**

- 用户名显示异常，不正确，并且无法理解是从哪里获取到的。
- 设置应该在插件界面内，但启动直接崩溃，导致无法重新配置路径。

**尝试解决方法:**

1. 尝试卸载插件。
2. 完全重启utools。
3. 删除`super-clipboard-data`文件夹。

问题仍然存在，需要进一步调查。

**Comment by ZiuChen** [comment]
感谢反馈，问题已经定位，会在下个版本修复。

**Comment by ZiuChen** [comment]
fixed
